name: onMainSync

on:
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'

      - name: Build
        run: swift build -v

      - name: Run tests with coverage
        run: xcodebuild test -scheme SwiftNetworker -destination 'platform=iOS Simulator,name=iPhone 11,OS=latest' -enableCodeCoverage YES -testPlan SwiftNetworkerPlan -resultBundlePath TestResults

      - name: Verify TestResults
        run: ls -alh TestResults.xcresult

      - name: Install llvm-cov
        run: |
          brew install llvm
          export PATH="/usr/local/opt/llvm/bin:$PATH"

      - name: Generate code coverage report
        run: |
          mkdir -p coverage
          xcrun llvm-profdata merge -sparse TestResults.xcresult/coverage.profdata -o coverage/coverage.profdata
          xcrun llvm-cov show \
            .build/debug/SwiftNetworkerPackageTests.xctest \
            -instr-profile=coverage/coverage.profdata \
            -ignore-filename-regex="(Tests/.*|README\\.md)" \
            -format=html \
            -output-dir=coverage

      - name: Generate coverage summary
        run: |
          xcrun llvm-cov export \
            .build/debug/SwiftNetworkerPackageTests.xctest \
            -instr-profile=coverage/coverage.profdata \
            -ignore-filename-regex="(Tests/.*|README\\.md)" \
            -format=json \
            > coverage/coverage.json

      - name: Verify Coverage Report
        run: cat coverage/coverage.json

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/coverage.json
          flags: unittests
          name: codecov-report
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
