name: onMainSync

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.3.1'
    - name: Build
      run: swift build -v

    - name: Run tests
      run: xcodebuild test -scheme SwiftNetworker -destination 'platform=iOS Simulator,name=iPhone 11,OS=latest' -enableCodeCoverage YES -resultBundlePath TestResults

    - name: Generate code coverage report
      run: xcrun xccov view --report --json TestResults.xcresult > coverage.json

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.json
        flags: unittests
        name: codecov-report
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Install jazzy
      run: gem install jazzy

    - name: Generate Documentation
      run: jazzy --module SwiftNetworker --output docs

    - name: Deploy Documentation to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./docs
